# Generated by Django 5.0.6 on 2024-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
